// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmntbwbkyxnydojpouyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbnRid2JreXhueWRvanBvdXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTQ4MDQsImV4cCI6MjA2ODkzMDgwNH0.8_4K0H42JEulrMnm5M5KTEKvC0lA7Ae2uwtba2YRNnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});